SYSROOT=/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS3.0.sdk

include theos/makefiles/common.mk

TWEAK_NAME = demoScreenCapture1
demoScreenCapture1_FILES = Tweak.xm
demoScreenCapture1_FRAMEWORKS = UIKit QuartzCore  CoreGraphics IOKit AVFoundation
demoScreenCapture1_PRIVATEFRAMEWORKS = UIKit QuartzCore CoreGraphics IOKit AVFoundation GraphicsServices
include $(THEOS_MAKE_PATH)/tweak.mk
