/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

@protocol UIAutoscrollContainer
- (struct CGRect)contentFrameForView:(id)arg1;
@property(nonatomic) struct CGPoint autoscrollContentOffset;
@end

