/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import <UIKit/UIWebDocumentView.h>

#import "UIAutoscrollContainer-Protocol.h"

@class DOMDocument, DOMHTMLElement, NSString, UIView<UITextSelectingContainer>;

@interface UIFieldEditor : UIWebDocumentView <UIAutoscrollContainer>
{
    DOMDocument *_document;
    DOMHTMLElement *_textElement;
    DOMHTMLElement *_sizeElement;
    NSString *_initialText;
    NSString *_currentStyle;
    UIView<UITextSelectingContainer> *_proxiedView;
    unsigned int _baseWritingDirectionIsRTL:1;
    unsigned int _changingView:1;
    unsigned int _disableNotifications:1;
    unsigned int _delegateRespondsToFieldEditorDidChange:1;
    unsigned int _delegateRespondsToShouldInsertText:1;
    unsigned int _delegateRespondsToShouldReplaceWithText:1;
    unsigned int _fieldEditorReentrancyGuard:1;
    unsigned int _isResigningFirstResponder:1;
    unsigned int _mouseWasDragged:1;
    unsigned int _reserved:21;
}

+ (id)activeFieldEditor;
+ (id)sharedFieldEditor;
+ (void)releaseSharedInstance;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)dealloc;
- (void)selectAll;
- (id)_responderForBecomeFirstResponder;
- (id)_textSelectingContainer;
- (struct _NSRange)selectionRange;
- (void)_selectNSRange:(struct _NSRange)arg1;
- (void)setSelection:(struct _NSRange)arg1;
- (void)revealSelection;
- (void)setTextSelectionBehavior:(int)arg1;
- (unsigned int)characterOffsetAtPoint:(struct CGPoint)arg1;
- (id)textInputTraits;
- (BOOL)keyboardInput:(id)arg1 shouldInsertText:(id)arg2 isMarkedText:(BOOL)arg3;
- (BOOL)keyboardInputShouldDelete:(id)arg1;
- (BOOL)keyboardInputChanged:(id)arg1;
- (void)keyboardInputChangedSelection:(id)arg1;
- (id)sizeStyleForRect:(struct CGRect)arg1;
- (void)becomeFieldEditorForView:(id)arg1;
- (void)_setTextElementStyle:(id)arg1;
- (void)setStyle:(id)arg1;
- (id)style;
- (id)textColorForCaretSelection;
- (void)_setTextElementString:(id)arg1;
- (void)setText:(id)arg1 andSetCaretSelectionAfterText:(BOOL)arg2;
- (id)text;
- (void)setCaretColor:(id)arg1;
- (int)scrollXOffset;
- (int)scrollYOffset;
- (void)setScrollXOffset:(int)arg1 scrollYOffset:(int)arg2;
- (void)setScrollXOffset:(int)arg1 scrollYOffset:(int)arg2 adjustForPurpleCaret:(BOOL)arg3;
- (struct CGSize)contentSize;
- (void)scrollSelectionToVisible:(BOOL)arg1;
- (void)scrollToMakeInlineHoleVisible;
- (void)webViewDidChange:(id)arg1;
- (BOOL)webView:(id)arg1 shouldChangeSelectedDOMRange:(id)arg2 toDOMRange:(id)arg3 affinity:(int)arg4 stillSelecting:(BOOL)arg5;
- (BOOL)webView:(id)arg1 shouldInsertText:(id)arg2 replacingDOMRange:(id)arg3 givenAction:(int)arg4;
- (BOOL)webView:(id)arg1 shouldDeleteDOMRange:(id)arg2;
- (BOOL)hasMarkedText;
- (id)proxiedView;
- (void)setFrame:(struct CGRect)arg1;
- (void)mouseDown:(struct __GSEvent *)arg1;
- (void)mouseDragged:(struct __GSEvent *)arg1;
- (void)mouseUp:(struct __GSEvent *)arg1;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)resumeWithNotification:(id)arg1;
- (id)customOverlayContainer;
- (id)automaticallySelectedOverlay;
- (BOOL)notificationsDisabled;
- (void)setNotificationsDisabled:(BOOL)arg1;
- (BOOL)mouseEventsChangeSelection;
- (id)selectionView;
- (id)interactionAssistant;
- (struct CGRect)selectionClipRect;
- (void)selectionChanged;
- (void)startAutoscroll:(struct CGPoint)arg1;
- (void)updateAutoscroll:(id)arg1;
- (void)autoscrollWillNotStart;
@property(nonatomic) struct CGPoint autoscrollContentOffset;
- (struct CGRect)contentFrameForView:(id)arg1;
- (void)setBaseWritingDirection:(int)arg1;
- (struct CGRect)caretRect;
- (struct CGRect)caretRectForVisiblePosition:(id)arg1;

@end

