/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import <UIKit/UIView.h>

#import "UIKeyboardImplGeometryDelegate-Protocol.h"

@class UIImage, UITextInputTraits;

@interface UIKeyboard : UIView <UIKeyboardImplGeometryDelegate>
{
    UIImage *m_snapshot;
    UITextInputTraits *m_defaultTraits;
    BOOL m_typingDisabled;
    BOOL m_minimized;
    BOOL m_respondingToImplGeometryChange;
    int m_orientation;
}

+ (id)activeKeyboard;
+ (void)_clearActiveKeyboard;
+ (void)initImplementationNow;
+ (void)removeAllDynamicDictionaries;
+ (struct CGSize)defaultSize;
+ (struct CGSize)defaultSizeForInterfaceOrientation:(int)arg1;
+ (struct CGRect)defaultFrameForInterfaceOrientation:(int)arg1;
+ (struct CGSize)defaultSizeForOrientation:(int)arg1;
+ (struct CGSize)sizeForInterfaceOrientation:(int)arg1;
+ (struct CGSize)keyboardSizeForInterfaceOrientation:(int)arg1;
- (void)autoAdjustOrientation;
- (void)autoAdjustOrientationForSize:(struct CGSize)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithDefaultSize;
- (void)dealloc;
- (void)setFrame:(struct CGRect)arg1;
- (void)updateLayout;
- (int)orientation;
- (int)interfaceOrientation;
- (BOOL)pointInside:(struct CGPoint)arg1 forEvent:(struct __GSEvent *)arg2;
- (BOOL)pointInside:(struct CGPoint)arg1 withEvent:(id)arg2;
- (void)prepareForGeometryChange;
- (void)geometryChangeDone:(BOOL)arg1;
- (void)removeAutocorrectPrompt;
- (void)acceptAutocorrection;
- (void)setCaretBlinks:(BOOL)arg1;
- (void)setCaretVisible:(BOOL)arg1;
- (BOOL)returnKeyEnabled;
- (void)setReturnKeyEnabled:(BOOL)arg1;
- (id)defaultTextInputTraits;
- (void)setDefaultTextInputTraits:(id)arg1;
- (id)delegate;
- (void)clearSnapshot;
- (void)takeSnapshot;
@property(nonatomic) BOOL typingEnabled;
- (void)activate;
- (BOOL)isActive;
- (void)deactivate;
- (void)movedFromSuperview:(id)arg1;
- (void)removeFromSuperview;
- (void)setNeedsDisplay;
- (void)displayLayer:(id)arg1;
- (int)textEffectsVisibilityLevel;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
@property(nonatomic, getter=isMinimized) BOOL minimized;
- (void)syncMinimizedStateToHardwareKeyboardAttachedState;
- (struct UIPeripheralAnimationGeometry)geometryForMinimize:(BOOL)arg1;
- (void)minimize;
- (void)maximize;
- (void)keyboardMinMaximized:(id)arg1 finished:(id)arg2 context:(id)arg3;
- (struct UIPeripheralAnimationGeometry)geometryForImplHeightDelta:(float)arg1;
- (void)prepareForImplBoundsHeightChange:(float)arg1 suppressNotification:(BOOL)arg2;
- (void)implBoundsHeightChangeDone:(float)arg1 suppressNotification:(BOOL)arg2;
- (BOOL)canDismiss;

@end

