/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import <UIKit/UIResponder.h>

//#import "NSCoding-Protocol.h"

@class CALayer, NSArray, NSMutableArray, UIViewController;

@interface UIView : UIResponder <NSCoding>
{
    CALayer *_layer;
    id _tapInfo;
    id _gestureInfo;
    NSMutableArray *_gestureRecognizers;
    NSArray *_subviewCache;
    float _charge;
    int _tag;
    UIViewController *_viewDelegate;
    struct {
        unsigned int userInteractionDisabled:1;
        unsigned int implementsDrawRect:1;
        unsigned int implementsDidScroll:1;
        unsigned int implementsMouseTracking:1;
        unsigned int hasBackgroundColor:1;
        unsigned int isOpaque:1;
        unsigned int becomeFirstResponderWhenCapable:1;
        unsigned int interceptMouseEvent:1;
        unsigned int deallocating:1;
        unsigned int debugFlash:1;
        unsigned int debugSkippedSetNeedsDisplay:1;
        unsigned int debugScheduledDisplayIsRequired:1;
        unsigned int isInAWindow:1;
        unsigned int isAncestorOfFirstResponder:1;
        unsigned int dontAutoresizeSubviews:1;
        unsigned int autoresizeMask:6;
        unsigned int patternBackground:1;
        unsigned int fixedBackgroundPattern:1;
        unsigned int dontAnimate:1;
        unsigned int superLayerIsView:1;
        unsigned int layerKitPatternDrawing:1;
        unsigned int multipleTouchEnabled:1;
        unsigned int exclusiveTouch:1;
        unsigned int hasViewController:1;
        unsigned int needsDidAppearOrDisappear:1;
        unsigned int gesturesEnabled:1;
        unsigned int deliversTouchesForGesturesToSuperview:1;
        unsigned int chargeEnabled:1;
        unsigned int skipsSubviewEnumeration:1;
        unsigned int needsDisplayOnBoundsChange:1;
        unsigned int hasTiledLayer:1;
        unsigned int hasLargeContent:1;
        unsigned int alwaysScaleContent:1;
    } _viewFlags;
}

+ (Class)layerClass;
- (id)init;
- (void)_createLayerWithFrame:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (void)dealloc;
@property(nonatomic, getter=isUserInteractionEnabled) BOOL userInteractionEnabled;
- (void)setCharge:(float)arg1;
- (float)charge;
- (void)_setChargeEnabled:(BOOL)arg1;
- (BOOL)_isChargeEnabled;
- (void)setTapDelegate:(id)arg1;
- (id)tapDelegate;
- (id)nextResponder;
- (int)_topToBottomLeftToRightViewCompare:(id)arg1;
- (id)_nextKeyResponder;
- (id)_previousKeyResponder;
- (void)_clearBecomeFirstResponderWhenCapable;
- (BOOL)_becomeFirstResponderWhenPossible;
- (void)startHeartbeat:(SEL)arg1 inRunLoopMode:(id)arg2;
- (void)stopHeartbeat:(SEL)arg1;
- (BOOL)cancelMouseTracking;
- (BOOL)cancelTouchTracking;
- (BOOL)canHandleSwipes;
- (int)swipe:(int)arg1 withEvent:(struct __GSEvent *)arg2;
- (void)_setBackgroundCGColor:(struct CGColor *)arg1;
- (struct CGColor *)_backgroundCGColor;
- (BOOL)_shouldAnimatePropertyWithKey:(id)arg1;
@property(readonly, retain, nonatomic) CALayer *layer; // @synthesize layer=_layer;
@property(nonatomic) int tag; // @synthesize tag=_tag;

@end

